"""Derive every web image from assets-src/ and write the intrinsic sizes React needs.

Originals live in assets-src/ and are never shipped. public/images/ holds only
derivatives. Run with:  npm run media
"""
from __future__ import annotations

import json
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "assets-src"
OUT = ROOT / "public/images"

# WebP quality for every derivative.
#
# Measured against the downscaled original, at 2000px: quality 78 scores 34.5 dB
# PSNR, quality 92 scores 40.4 dB, and lossless scores infinity by definition.
# Above roughly 40 dB a re-encode is not distinguishable from the source by eye,
# so 92 is where the curve stops paying: 95 costs another 17% for 1.5 dB.
#
# Lossless was tried and is the wrong lever. These sources are JPEGs, so
# lossless WebP spends 9 MB per photograph faithfully preserving the original's
# own JPEG artifacts — it is not a better picture, only a bigger file, and at
# 394 MB the site stopped being deployable. The true masters live in
# assets-src/ and are never shipped; nothing is lost by not duplicating them
# here.
QUALITY = 92

# A rung within 15% of the one below is not worth its bytes: the browser would
# be choosing between two indistinguishable files.
MIN_STEP = 1.15

# Source corrections. A few files were saved with the camera's rotation baked
# out of the EXIF but not out of the pixels, so nothing downstream can know
# they are sideways. Degrees clockwise.
ROTATIONS: dict[str, dict[str, int]] = {
    "art": {},
    "photo": {"10": 270},
}

# One widths ladder per role. Art needs a large size for the viewer dialog;
# photographs are only ever shown in a masonry column or full-bleed viewer.
PLAN = [
    ("art", SRC / "art", OUT / "art", (400, 800, 1600)),
    ("photo", SRC / "photo", OUT / "photo", (640, 1280, 2000)),
]


def slug(path: Path) -> str:
    """art07.jpg -> 07 ; photo-07.jpg -> 07"""
    return path.stem.replace("photo-", "").replace("art", "")


def derive(source: Path, out_dir: Path, key: str, widths: tuple[int, ...], rotate: int = 0) -> dict:
    with Image.open(source) as raw:
        image = ImageOps.exif_transpose(raw).convert("RGB")
        if rotate:
            image = image.rotate(-rotate, expand=True)
        full_w, full_h = image.size

        # The ladder is CAPPED by the master, not TRUNCATED by it. Dropping
        # every rung wider than the source is right — nothing is ever
        # upscaled — but it used to stop there, so a 720px drawing shipped at
        # 400 and the drum upscaled it 1.6x on screen. When the rungs run out
        # below the master, the master's own width becomes the last rung.
        rungs = [w for w in widths if w <= full_w * 1.05]
        if len(rungs) < len(widths) and full_w > (rungs[-1] if rungs else 0) * MIN_STEP:
            rungs.append(full_w)

        for width in rungs:
            target = out_dir / f"{key}-{width}.webp"
            newest = max(source.stat().st_mtime, Path(__file__).stat().st_mtime)
            if target.exists() and target.stat().st_mtime > newest:
                continue
            copy = image.copy()
            copy.thumbnail((width, full_h), Image.LANCZOS)
            copy.save(target, "WEBP", quality=QUALITY, method=6)
        # The byte size of every rung, so the loading screen can weigh what it
        # is waiting for instead of counting files as if they were equal. A
        # 2 MB photograph and a 60 KB one are not the same wait.
        weights = {str(w): (out_dir / f"{key}-{w}.webp").stat().st_size for w in rungs}
    return {"w": full_w, "h": full_h, "widths": rungs, "bytes": weights}


def main() -> None:
    manifest: dict[str, dict] = {}
    for role, src_dir, out_dir, widths in PLAN:
        out_dir.mkdir(parents=True, exist_ok=True)
        entries = {}
        for source in sorted(src_dir.iterdir()):
            if source.suffix.lower() not in {".jpg", ".jpeg", ".png", ".webp"}:
                continue
            key = slug(source)
            entries[key] = derive(source, out_dir, key, widths, ROTATIONS[role].get(key, 0))
            print(f"{role}/{key}  {entries[key]['w']}x{entries[key]['h']} -> {entries[key]['widths']}")
        manifest[role] = entries

    target = ROOT / "src/data/media.ts"
    target.write_text(
        "// GENERATED by scripts/build-media.py — do not edit.\n"
        "export interface MediaEntry {\n  w: number\n  h: number\n  widths: number[]\n  /** Byte size of each rung, keyed by width. */\n  bytes: Record<string, number>\n}\n\n"
        "export const media: Record<'art' | 'photo', Record<string, MediaEntry>> =\n  "
        + json.dumps(manifest, indent=2, sort_keys=True).replace("\n", "\n  ")
        + " as const\n"
    )
    print(f"\nwrote {target.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
